var express = require('express');
var app = express();

app.get('/dynamic', function (req, res) {
  //uncomment the next line to break in code in Chrome.
  //debugger;
  res.send('Content generated by express js code.<a href="/">back</a>');
});
app.use(express.static('static'));
var server = app.listen(8888, function() {
    console.log('Listening on port %d', server.address().port);
});
